---
all:
  children:
    cisco:
      hosts:
        cisco-small-01:
          ansible_connection: ansible.netcommon.network_cli
          ansible_network_os: ios
          ansible_host: ip_address
          ansible_port: 22
          ansible_ssh_common_arg: -o KexAlgorithms=diffie-hellman-group1-sha1
        cisco-small-02:
          ansible_connection: ansible.netcommon.network_cli
          ansible_network_os: ios
          ansible_host: ip_address
          ansible_port: 22
          ansible_ssh_common_arg: -o KexAlgorithms=diffie-hellman-group1-sha1
        cisco-small-03:
          ansible_connection: ansible.netcommon.network_cli
          ansible_network_os: ios
          ansible_host: ip_address
          ansible_port: 22
          ansible_ssh_common_arg: -o KexAlgorithms=diffie-hellman-group1-sha1

    mikrotik:
      hosts:
        apmik01lte:
          ansible_connection: network_cli
          ansible_network_os: routeros
          ansible_host: ip_address
        apmik02biglte:
          ansible_connection: network_cli
          ansible_network_os: routeros
          ansible_host: ip_address
        apmik03:
          ansible_connection: network_cli
          ansible_network_os: routeros
          ansible_host: ip_address
        apmik04:
          ansible_connection: network_cli
          ansible_network_os: routeros
          ansible_host: ip_address